#include QMK_KEYBOARD_H

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_ortho_4x4(KC_P7, KC_P8, KC_P9, KC_PSLS, KC_P4, KC_P5, KC_P6, LT(2,KC_PEQL), KC_P1, KC_P2, KC_P3, TG(1), KC_P0, KC_PDOT, KC_PMNS, KC_PENT), //numpad layer
	[1] = LAYOUT_ortho_4x4(KC_ESC, KC_F1, KC_F2, KC_BSPC, KC_D, KC_F, KC_J, KC_K, KC_Z, KC_X, KC_C, KC_TRNS, KC_UP, KC_SPC, KC_SPC, KC_DOWN), //osu! layer
	[2] = LAYOUT_ortho_4x4(RESET, KC_TRNS, KC_TRNS, BL_TOGG, RGB_TOG, RGB_MODE_REVERSE, RGB_MODE_FORWARD, KC_TRNS, RGB_HUI, RGB_SAI, RGB_VAI, BL_INC, RGB_HUD, RGB_SAD, RGB_VAD, BL_DEC) //led layer
};

// osu! layer
const rgblight_segment_t PROGMEM my_layer1_layer[] = RGBLIGHT_LAYER_SEGMENTS(
	{0,2,HSV_MAGENTA} // Light 2 LEDS, starting with 1
);
// led layer
const rgblight_segment_t PROGMEM my_layer2_layer[] = RGBLIGHT_LAYER_SEGMENTS(
	{0,2,HSV_WHITE} // Light 2 LEDS, starting with 1
);

const rgblight_segment_t* const PROGMEM my_rgb_layers[] = RGBLIGHT_LAYERS_LIST(
	my_layer1_layer,
	my_layer2_layer
);

void keyboard_post_init_user(void) {
	rgblight_layers = my_rgb_layers;
}

//layer_state_t default_layer_state_set_user(layer_state_t state){
//	rgblight_set_layer_state(1, layer_state_cmp(state, 1));
//	return state;
//}

layer_state_t layer_state_set_user(layer_state_t state) {
	rgblight_set_layer_state(1, layer_state_cmp(state, 2));
	rgblight_set_layer_state(2, layer_state_cmp(state, 3));
	return state;
}