#include QMK_KEYBOARD_H

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_ortho_4x4(KC_P7, KC_P8, KC_P9, KC_PSLS, KC_P4, KC_P5, KC_P6, LT(2,KC_PEQL), KC_P1, KC_P2, KC_P3, TG(1), KC_P0, KC_PDOT, KC_PMNS, KC_PENT),
	[1] = LAYOUT_ortho_4x4(KC_ESC, KC_F1, KC_F2, KC_BSPC, KC_D, KC_F, KC_J, KC_K, KC_Z, KC_X, KC_C, KC_TRNS, KC_UP, KC_SPC, KC_SPC, KC_DOWN),
	[2] = LAYOUT_ortho_4x4(RESET, KC_TRNS, KC_TRNS, BL_TOGG, RGB_TOG, RGB_MODE_REVERSE, RGB_MODE_FORWARD, KC_TRNS, RGB_HUI, RGB_SAI, RGB_VAI, BL_INC, RGB_HUD, RGB_SAD, RGB_VAD, BL_DEC)
};
